### ISSUE TITLE
flesh out content

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/trainer-training#15]
It would be great if this content was more stand-along (i.e. could be led by someone who hadn't authored the content). These discussion questions are assumedly leading to specific conversations or at least are meant to bring up specific key take away points that are important for new Trainers to know. We should add narrative text to the lesson to bring those messages out explicitly.

**Comment by karenword** [comment]
The problem with doing this is that trainees are pointed at these curriculum pages, and these questions are provided as 'homework.' While there often are a few key take-home points of discussion, more often it is about practice thinking about and imaginatively applying the content in the readings, and arriving at those key points is a process of discovery. Providing narrative text in advance would actively interfere with that process. I suggest creating a guide for operating this training that is separate from this repository.
