### ISSUE TITLE
Use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by annajiat** [carpentries/trainer-training#56]
Being inspired by https://github.com/carpentries/instructor-training/issues/1237

updated https://pad.carpentries.org/trainer-training
with the https version of redirected links

**pad of pads**
new: https://pad.carpentries.org/pad-of-pads
old: http://pad.software-carpentry.org/pad-of-pads

**code of conduct** 
new: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html
old: http://software-carpentry.org/conduct.html

**Comment by ndporter** [comment]
Looks complete and doesn't require action on git. Recommend someone with write privileges to trainer-training close as completed.
