### ISSUE TITLE
Link to book goes to 1st ed (but should go to 2nd)

### ISSUE THREAD

**Issue by joelnitta** [carpentries/trainer-training#64]
The link to *How Learning Works* goes to the first edition:

https://github.com/carpentries/trainer-training/blob/b6c3986e1a9a75afe130bc57476b586aebcd680b/episodes/01-week1_discussion_questions.md?plain=1#L25

but the 2nd edition is actually used. So the link should be updated. The same link may appear in other places, I haven't checked.

**Comment by ErinBecker** [comment]
Thanks @joelnitta! I thought I had found all of those, but I missed that one. Fixed now with https://github.com/carpentries/trainer-training/pull/65.
